import type {Metadata} from "next";
import "./globals.css";
import MainHeader from "@/components/Header/MainHeader";
import PopupContextCenter from "@/components/PopupContextCenter";
import PopupButtomContext from "@/components/PopupButtomContext";
import MainFooter from "@/components/Footer/MainFooter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="pl">
        <body
            className={`relative`}
        >
        <PopupContextCenter>
            <PopupButtomContext>
                <MainHeader></MainHeader>
                {children}
                <MainFooter/>
            </PopupButtomContext>
        </PopupContextCenter>
        </body>
        </html>
    );
}
