import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/Header/MainHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={``}
      >
        <MainHeader></MainHeader>
        {children}
        <div className={'border-2'}>Footer</div>
      </body>
    </html>
  );
}
